"""spires-contract: data-interface contracts for the SPIReS package family."""

# Version from setuptools_scm (git tags)
from importlib.metadata import version, PackageNotFoundError

try:
    __version__ = version("spires_contract")
except PackageNotFoundError:
    __version__ = "unknown"

from spires_contract._validate import ContractError
from spires_contract.alignment import (
    validate_coordinate_alignment,
    validate_spatial_alignment,
)
from spires_contract.clusters import clusters_present, validate_clusters
from spires_contract.data import SpiresData, validate_spires_data
from spires_contract.inversion_input import validate_for_inversion
from spires_contract.inversion_exclusion import (
    inversion_exclusion_metadata,
    validate_inversion_exclusion,
)
from spires_contract.lut import (
    canonical_lut_unit,
    validate_albedo_lut,
    validate_lut,
    validate_reflectance_lut,
)
from spires_contract.persistence import (
    ALBEDO_RESULT_VARIABLES,
    COMPLETION_STATUS_COMPLETE,
    CONTENT_PROFILE_INVERSION_RAW,
    CONTENT_PROFILE_POSTPROCESSED_RAW,
    DERIVED_RESULT_LONG_NAMES,
    DERIVED_RESULT_UNITS,
    OPERATION_ALBEDO,
    OPERATION_CANOPY_CORRECTION,
    OPERATION_DELTA_VIS,
    OPERATION_ICE_ADJUSTMENT,
    OPERATION_RADIATIVE_FORCING,
    OPERATION_RESULT_VARIABLES,
    PERSISTED_ATTR_ACQUISITION_TIME,
    PERSISTED_ATTR_BACKGROUND_VARIABLE,
    PERSISTED_ATTR_COMPLETED_OPERATIONS,
    PERSISTED_ATTR_COMPLETED_STAGES,
    PERSISTED_ATTR_COMPLETION_STATUS,
    PERSISTED_ATTR_CONTENT_PROFILE,
    PERSISTED_ATTR_CREATED_AT,
    PERSISTED_ATTR_GRID_DIGEST,
    PERSISTED_ATTR_PACKAGE_VERSIONS,
    PERSISTED_ATTR_PLATFORM,
    PERSISTED_ATTR_PRESENT_GROUPS,
    PERSISTED_ATTR_PRODUCT,
    PERSISTED_ATTR_PRODUCT_CONTENTS,
    PERSISTED_ATTR_PRODUCT_TYPE,
    PERSISTED_ATTR_PROVENANCE,
    PERSISTED_ATTR_SCHEMA_VERSION,
    PERSISTED_ATTR_SENSOR,
    PERSISTED_ATTR_SPATIAL_ID,
    PERSISTED_ATTR_UPDATED_AT,
    PERSISTED_GROUP_ANCILLARY,
    PERSISTED_GROUP_BACKGROUND,
    PERSISTED_GROUP_RESULTS,
    PERSISTED_GROUP_SCENE,
    PERSISTED_GROUPS,
    PERSISTED_PRODUCT_TYPE,
    PERSISTED_SCHEMA_VERSION,
    PRODUCT_CONTENTS_FULL,
    PRODUCT_CONTENTS_RESULTS_SUBSET,
    PersistedProductMetadata,
    ProductIdentity,
    validate_persisted_data,
    validate_persisted_grid,
    validate_persisted_metadata,
)
from spires_contract.results import validate_results

__all__ = [
    "ContractError",
    "ALBEDO_RESULT_VARIABLES",
    "COMPLETION_STATUS_COMPLETE",
    "CONTENT_PROFILE_INVERSION_RAW",
    "CONTENT_PROFILE_POSTPROCESSED_RAW",
    "DERIVED_RESULT_LONG_NAMES",
    "DERIVED_RESULT_UNITS",
    "OPERATION_ALBEDO",
    "OPERATION_CANOPY_CORRECTION",
    "OPERATION_DELTA_VIS",
    "OPERATION_ICE_ADJUSTMENT",
    "OPERATION_RADIATIVE_FORCING",
    "OPERATION_RESULT_VARIABLES",
    "PERSISTED_ATTR_ACQUISITION_TIME",
    "PERSISTED_ATTR_BACKGROUND_VARIABLE",
    "PERSISTED_ATTR_COMPLETED_OPERATIONS",
    "PERSISTED_ATTR_COMPLETED_STAGES",
    "PERSISTED_ATTR_COMPLETION_STATUS",
    "PERSISTED_ATTR_CONTENT_PROFILE",
    "PERSISTED_ATTR_CREATED_AT",
    "PERSISTED_ATTR_GRID_DIGEST",
    "PERSISTED_ATTR_PACKAGE_VERSIONS",
    "PERSISTED_ATTR_PLATFORM",
    "PERSISTED_ATTR_PRESENT_GROUPS",
    "PERSISTED_ATTR_PRODUCT",
    "PERSISTED_ATTR_PRODUCT_CONTENTS",
    "PERSISTED_ATTR_PRODUCT_TYPE",
    "PERSISTED_ATTR_PROVENANCE",
    "PERSISTED_ATTR_SCHEMA_VERSION",
    "PERSISTED_ATTR_SENSOR",
    "PERSISTED_ATTR_SPATIAL_ID",
    "PERSISTED_ATTR_UPDATED_AT",
    "PERSISTED_GROUP_ANCILLARY",
    "PERSISTED_GROUP_BACKGROUND",
    "PERSISTED_GROUP_RESULTS",
    "PERSISTED_GROUP_SCENE",
    "PERSISTED_GROUPS",
    "PERSISTED_PRODUCT_TYPE",
    "PERSISTED_SCHEMA_VERSION",
    "PRODUCT_CONTENTS_FULL",
    "PRODUCT_CONTENTS_RESULTS_SUBSET",
    "PersistedProductMetadata",
    "ProductIdentity",
    "SpiresData",
    "canonical_lut_unit",
    "clusters_present",
    "inversion_exclusion_metadata",
    "validate_coordinate_alignment",
    "validate_clusters",
    "validate_for_inversion",
    "validate_inversion_exclusion",
    "validate_albedo_lut",
    "validate_lut",
    "validate_persisted_data",
    "validate_persisted_grid",
    "validate_persisted_metadata",
    "validate_reflectance_lut",
    "validate_results",
    "validate_spatial_alignment",
    "validate_spires_data",
    "__version__",
]
